"""The library screen: F-38 to F-43 and F-45.

The tests that matter here are the ones a later refactor would quietly
break: that a page of history costs one query and no files, that a
regeneration is offered as a new entry and never as the old one, that a
deletion says exactly what it will remove, and that a job an abnormal
termination left behind is neither played nor regenerated by looking at it.
"""

from __future__ import annotations

import ast
import hashlib
from pathlib import Path

import pytest
from PySide6.QtCore import Qt
from PySide6.QtTest import QTest
from PySide6.QtWidgets import (
    QAbstractButton,
    QApplication,
    QComboBox,
    QDialog,
    QLineEdit,
    QStackedWidget,
    QWidget,
)

from echoact import paths
from echoact.db.store import ResultIntegrity, Store
from echoact.domain import (
    Budget,
    Gender,
    Job,
    JobKind,
    JobState,
    Language,
    RequestPath,
    Result,
    RetentionMode,
    SpeakingStyle,
    VoiceSettings,
)
from echoact.models.catalog import MANIFEST
from echoact.policy import LIST_PAGE_DEFAULT, LIST_PAGE_MAX, ONEOFF_RESULT_TTL_S
from echoact.ui import i18n, library, theme
from echoact.ui.library import (
    DeleteConfirmDialog,
    DocumentsPane,
    HistoryPane,
    LibraryScreen,
    build_job_row,
    playability,
    retention_text,
    scope_lines,
    state_text,
)

NOW = 1_700_000_000.0
KOREAN = "에코액트는 문서를 소리내어 읽어 줍니다."
ENGLISH = "EchoAct reads your documents aloud on this machine."


# ---------------------------------------------------------------- setup ---


@pytest.fixture
def data_dir(tmp_path, monkeypatch):
    """Never the real user data directory.  ``paths.data_dir`` is cached, so
    the cache is cleared on the way in and on the way out."""
    monkeypatch.setenv("ECHOACT_DATA_DIR", str(tmp_path))
    paths.data_dir.cache_clear()
    paths.ensure_tree()
    yield tmp_path
    paths.data_dir.cache_clear()


@pytest.fixture
def store(data_dir):
    s = Store()
    yield s
    s.close()


@pytest.fixture(scope="session")
def app() -> QApplication:
    return QApplication.instance() or QApplication([])


@pytest.fixture
def clock():
    return lambda: NOW


def _settings(model_id: str = "supertonic-3", voice: str = "F1") -> VoiceSettings:
    return VoiceSettings(
        model_id=model_id,
        language=Language.KO,
        gender=Gender.FEMALE,
        voice_id=voice,
        style=SpeakingStyle.NATURAL,
        tempo=1.0,
    )


def _job(
    store: Store,
    job_id: str,
    *,
    state: JobState = JobState.COMPLETE,
    retention: RetentionMode = RetentionMode.RETAINED,
    text: str | None = KOREAN,
    model_id: str = "supertonic-3",
    voice: str = "F1",
    created_at: float = NOW - 60,
    path: RequestPath = RequestPath.GUI,
) -> Job:
    """A history entry already in a terminal state, the way the library
    meets one: the engine is not involved in any of these tests."""
    job = Job(
        job_id=job_id,
        kind=JobKind.SPEECH,
        request_path=path,
        owner_client_id="cli_owner",
        state=JobState.ACCEPTED,
        source_text=text or "",
        settings=_settings(model_id, voice),
        budget=Budget(cpu_percent=20, memory_bytes=2 << 30, intra_op_threads=2),
        retention=retention,
        created_at=created_at,
    )
    store.create_job(job, at=created_at)
    if state is not JobState.ACCEPTED:
        if state in (JobState.COMPLETE, JobState.CANCELED):
            store.update_job_state(job_id, JobState.GENERATING, at=created_at + 1)
        if state is JobState.CANCELED:
            store.update_job_state(job_id, JobState.CANCELING, at=created_at + 2)
        if state is JobState.FAILED:
            store.record_job_error(job_id, "GENERATION_FAILED", at=created_at + 3)
        else:
            store.update_job_state(job_id, state, at=created_at + 3)
    if text is None:
        store.clear_job_source_text(job_id)
    return job


def _attach(
    store: Store,
    job_id: str,
    *,
    exists: bool = True,
    truncated: bool = False,
    expires_at: float | None = None,
    frames: int = 44_100,
) -> Result:
    payload = b"RIFF" + b"\0" * 2044
    relative = f"{job_id}.wav"
    if exists:
        target = store.audio_root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload[:64] if truncated else payload)
    return store.attach_result(
        Result(
            result_id="",
            job_id=job_id,
            sample_rate=44_100,
            channels=1,
            sample_width_bits=16,
            frame_count=frames,
            byte_size=len(payload),
            digest=hashlib.sha256(payload).hexdigest(),
            created_at=NOW - 30,
            expires_at=expires_at,
            relative_path=relative,
        ),
        at=NOW - 30,
    )


def _summary(store: Store, job_id: str):
    for item in store.list_jobs(limit=LIST_PAGE_MAX).items:
        if item.job_id == job_id:
            return item
    raise AssertionError(f"no summary for {job_id}")


def _screen(store, clock) -> LibraryScreen:
    return LibraryScreen(store, theme.LIGHT, manifest=MANIFEST, clock=clock)


def _history(store, clock) -> HistoryPane:
    pane = HistoryPane(store, theme.LIGHT, manifest=MANIFEST, clock=clock)
    pane.refresh()
    return pane


def _documents(store) -> DocumentsPane:
    pane = DocumentsPane(store, theme.LIGHT)
    pane.refresh()
    return pane


def _cells(pane: HistoryPane, row: int) -> list[str]:
    item = pane.tree.topLevelItem(row)
    return [item.text(c) for c in range(pane.tree.columnCount())]


# ------------------------------------------------------- row text (F-39) ---


def test_an_interrupted_job_reads_as_interrupted_not_as_unfinished() -> None:
    """F-45: a forced termination leaves a state of its own, and the word
    for it is not "failed" and not "still going"."""
    assert state_text(JobState.INTERRUPTED) == "Interrupted"
    assert state_text(JobState.INTERRUPTED) != state_text(JobState.FAILED)
    assert state_text(JobState.INTERRUPTED) != state_text(JobState.GENERATING)


def test_a_row_reports_the_stored_audio_length_without_a_file(store) -> None:
    _job(store, "job_len")
    _attach(store, "job_len", frames=44_100 * 5)
    row = build_job_row(_summary(store, "job_len"), now=NOW)
    assert row.length == "0:05"


def test_a_retained_entry_says_it_is_kept_until_deleted(store) -> None:
    """F-42: whether an item is retained is visible on the row."""
    _job(store, "job_keep", retention=RetentionMode.RETAINED)
    _attach(store, "job_keep")
    assert retention_text(_summary(store, "job_keep"), now=NOW) == "Kept until you delete it"


def test_a_one_off_entry_says_when_its_audio_expires(store) -> None:
    """F-42 requires the expiry to be conveyed, not merely the mode."""
    _job(store, "job_once", retention=RetentionMode.ONE_OFF)
    result = _attach(store, "job_once", expires_at=NOW + ONEOFF_RESULT_TTL_S)
    summary = _summary(store, "job_once")
    assert retention_text(summary, expires_at=result.expires_at, now=NOW) == (
        "One-off · expires in about 1.0 h"
    )
    # ...and it counts down rather than repeating the policy figure.
    assert retention_text(summary, expires_at=result.expires_at, now=NOW + 1_800) == (
        "One-off · expires in about 30 min"
    )
    assert retention_text(summary, expires_at=result.expires_at, now=NOW + 7_200) == (
        "One-off · the audio has expired"
    )


def test_a_one_off_without_a_stored_expiry_says_what_actually_ends_it(store) -> None:
    """4.1 ties a GUI one-off to the app closing rather than to a clock, so
    the row says that instead of inventing a time."""
    _job(store, "job_gui", retention=RetentionMode.ONE_OFF)
    _attach(store, "job_gui", expires_at=None)
    assert (
        retention_text(_summary(store, "job_gui"), expires_at=None, now=NOW)
        == "One-off · removed when the app closes"
    )


# ------------------------------------------------- why it will not play ---


def test_an_interrupted_entry_says_the_app_closed_and_cannot_be_played(store) -> None:
    _job(store, "job_int", state=JobState.INTERRUPTED)
    verdict = playability(_summary(store, "job_int"))
    assert not verdict.playable
    assert "closed before this finished" in verdict.reason


def test_a_missing_result_file_says_so_rather_than_failing_on_play(store) -> None:
    """F-45: the reason playback is unavailable is given up front."""
    _job(store, "job_gone")
    result = _attach(store, "job_gone", exists=False)
    assert store.verify_result(result.result_id) is ResultIntegrity.MISSING
    verdict = playability(_summary(store, "job_gone"))
    assert not verdict.playable
    assert verdict.short == "audio missing"


def test_a_result_that_fails_its_digest_says_so(store) -> None:
    _job(store, "job_bad")
    result = _attach(store, "job_bad", truncated=True)
    assert store.verify_result(result.result_id) is ResultIntegrity.CORRUPT
    verdict = playability(_summary(store, "job_bad"))
    assert not verdict.playable
    assert verdict.short == "audio damaged"
    assert "integrity" in verdict.reason


def test_an_expired_one_off_result_is_not_offered_for_playback(store) -> None:
    _job(store, "job_old", retention=RetentionMode.ONE_OFF)
    _attach(store, "job_old", expires_at=NOW - 10)
    verdict = playability(_summary(store, "job_old"), expired=True)
    assert not verdict.playable
    assert verdict.short == "audio expired"


def test_a_sound_result_is_playable(store) -> None:
    _job(store, "job_ok")
    result = _attach(store, "job_ok")
    assert store.verify_result(result.result_id) is ResultIntegrity.OK
    assert playability(_summary(store, "job_ok")).playable


# ------------------------------------------------------ documents (F-38) ---


def test_the_document_list_shows_both_timestamps_and_a_size(app, store) -> None:
    store.save_document("Notes", "본문입니다", at=NOW - 500)
    pane = _documents(store)
    assert pane.tree.topLevelItemCount() == 1
    item = pane.tree.topLevelItem(0)
    assert item.text(0) == "Notes"
    assert item.text(1) and item.text(1) != "—"  # created
    assert item.text(2) and item.text(2) != "—"  # edited
    assert item.text(3) == "5"


def test_an_untitled_document_still_has_a_row_to_click(app, store) -> None:
    store.save_document("   ", "body", at=NOW)
    pane = _documents(store)
    assert pane.tree.topLevelItem(0).text(0) == "Untitled"


def test_documents_are_searched_by_title_and_by_retained_body_text(app, store) -> None:
    """F-40 searches both, and the pane must not silently search only one."""
    store.save_document("Shopping list", "우유와 빵", at=NOW - 10)
    store.save_document("Meeting", "quarterly revenue notes", at=NOW - 5)
    pane = _documents(store)

    pane.search.setText("Shopping")
    pane._search_now()
    assert [pane.tree.topLevelItem(0).text(0)] == ["Shopping list"]

    pane.search.setText("revenue")
    pane._search_now()
    assert [pane.tree.topLevelItem(0).text(0)] == ["Meeting"]

    pane.search.setText("우유")
    pane._search_now()
    assert pane.tree.topLevelItemCount() == 1


def test_a_search_that_matches_nothing_says_so_rather_than_looking_broken(
    app, store
) -> None:
    store.save_document("Notes", "body", at=NOW)
    pane = _documents(store)
    pane.search.setText("nothing like this")
    pane._search_now()
    assert pane.tree.topLevelItemCount() == 0
    assert pane.status.text() == "Nothing matches that search"


def test_enter_on_a_document_asks_the_window_to_open_it(app, store) -> None:
    """N-30: the list is usable with the arrow keys and Enter alone."""
    store.save_document("First", "a", at=NOW - 2)
    store.save_document("Second", "b", at=NOW - 1)
    pane = _documents(store)
    opened: list[str] = []
    pane.open_document.connect(opened.append)

    QTest.keyClick(pane.tree, Qt.Key.Key_Down)
    QTest.keyClick(pane.tree, Qt.Key.Key_Return)

    assert len(opened) == 1
    assert opened[0] == pane.tree.currentItem().data(0, Qt.ItemDataRole.UserRole)
    assert pane.tree.currentItem().text(0) == "First"  # newest first, so row 1 is older


# -------------------------------------------------------- paging (4.1) ---


def test_a_page_of_history_holds_the_default_twenty_rows(app, store, clock) -> None:
    for i in range(25):
        _job(store, f"job_{i:02d}", created_at=NOW - i)
    pane = _history(store, clock)
    assert pane.tree.topLevelItemCount() == LIST_PAGE_DEFAULT
    assert pane.pages.range_label.text() == "1–20 of 25"


def test_the_largest_page_offered_is_the_policy_ceiling(app, store, clock) -> None:
    """4.1 allows 100 per response; offering more would be a control that
    lies, because the store clamps whatever it is handed."""
    assert library.PAGE_SIZES == (LIST_PAGE_DEFAULT, LIST_PAGE_MAX)
    for i in range(25):
        _job(store, f"job_{i:02d}", created_at=NOW - i)
    pane = _history(store, clock)
    pane.pages.size.setCurrentIndex(1)
    assert pane.pages.page_size == LIST_PAGE_MAX
    assert pane.tree.topLevelItemCount() == 25


def test_the_next_page_shows_the_rest_and_then_stops(app, store, clock) -> None:
    for i in range(25):
        _job(store, f"job_{i:02d}", created_at=NOW - i)
    pane = _history(store, clock)
    assert not pane.pages.previous.isEnabled()
    pane.pages.next.click()
    assert pane.tree.topLevelItemCount() == 5
    assert pane.pages.range_label.text() == "21–25 of 25"
    assert not pane.pages.next.isEnabled()
    assert pane.pages.previous.isEnabled()


# ------------------------------------------- what a list is allowed to do ---


def test_listing_history_reads_no_audio_file(app, store, clock, monkeypatch) -> None:
    """F-40: a list is displayed without reading whole audio files.

    The shallow integrity check the detail panel runs is a ``stat``; opening
    the file is what this forbids, and it is what a digest would need.
    """
    opened: list[str] = []
    real_open = Path.open

    def spy(self, *args, **kwargs):
        if self.suffix == ".wav":
            opened.append(str(self))
        return real_open(self, *args, **kwargs)

    for i in range(5):
        _job(store, f"job_{i}", created_at=NOW - i)
        _attach(store, f"job_{i}")
    monkeypatch.setattr(Path, "open", spy)
    pane = _history(store, clock)
    assert pane.tree.topLevelItemCount() == 5
    assert opened == []


def test_listing_history_loads_only_the_snapshot_of_the_entry_it_opens(
    app, store, clock, monkeypatch
) -> None:
    """F-56 makes the body-text-free summary the default; the snapshot is a
    request of its own, so a page of twenty rows is not twenty of them."""
    asked: list[str] = []
    original = store.get_job_text

    def spy(job_id: str) -> str | None:
        asked.append(job_id)
        return original(job_id)

    for i in range(10):
        _job(store, f"job_{i}", created_at=NOW - i)
    monkeypatch.setattr(store, "get_job_text", spy)
    pane = _history(store, clock)
    assert pane.tree.topLevelItemCount() == 10
    assert asked == ["job_0"]  # the row selection opened, and nothing else


# -------------------------------------------------------- filters (F-40) ---


def test_history_filters_by_completion_state(app, store, clock) -> None:
    _job(store, "job_done", state=JobState.COMPLETE, created_at=NOW - 3)
    _job(store, "job_int", state=JobState.INTERRUPTED, created_at=NOW - 2)
    _job(store, "job_fail", state=JobState.FAILED, created_at=NOW - 1)
    pane = _history(store, clock)
    assert pane.tree.topLevelItemCount() == 3

    pane.state.setCurrentIndex(pane.state.findText("Interrupted"))
    assert pane.tree.topLevelItemCount() == 1
    assert pane.tree.topLevelItem(0).data(0, Qt.ItemDataRole.UserRole) == "job_int"

    pane.state.setCurrentIndex(pane.state.findText("Failed"))
    assert pane.tree.topLevelItem(0).data(0, Qt.ItemDataRole.UserRole) == "job_fail"


def test_history_filters_by_model(app, store, clock) -> None:
    _job(store, "job_a", model_id="supertonic-3", created_at=NOW - 2)
    _job(store, "job_b", model_id="some-other-model", created_at=NOW - 1)
    pane = _history(store, clock)
    assert pane.tree.topLevelItemCount() == 2
    pane.model.setCurrentIndex(1)
    assert pane.model.currentData() == "supertonic-3"
    assert pane.tree.topLevelItemCount() == 1
    assert pane.tree.topLevelItem(0).data(0, Qt.ItemDataRole.UserRole) == "job_a"


def test_history_filters_by_date(app, store, clock) -> None:
    _job(store, "job_now", created_at=NOW - 60)
    _job(store, "job_old", created_at=NOW - 40 * 86_400)
    pane = _history(store, clock)
    assert pane.tree.topLevelItemCount() == 2
    pane.date.setCurrentIndex(pane.date.findText("Today"))
    assert pane.tree.topLevelItemCount() == 1
    assert pane.tree.topLevelItem(0).data(0, Qt.ItemDataRole.UserRole) == "job_now"
    pane.date.setCurrentIndex(pane.date.findText("Last 30 days"))
    assert pane.tree.topLevelItemCount() == 1


def test_history_filters_by_whether_anything_is_being_kept(app, store, clock) -> None:
    """F-42's distinction is not only shown, it is answerable."""
    _job(store, "job_keep", retention=RetentionMode.RETAINED, created_at=NOW - 2)
    _job(store, "job_once", retention=RetentionMode.ONE_OFF, created_at=NOW - 1)
    pane = _history(store, clock)
    pane.retention.setCurrentIndex(pane.retention.findText("One-off"))
    assert pane.tree.topLevelItemCount() == 1
    assert pane.tree.topLevelItem(0).data(0, Qt.ItemDataRole.UserRole) == "job_once"


def test_an_empty_filtered_list_says_the_filters_are_why(app, store, clock) -> None:
    _job(store, "job_done", state=JobState.COMPLETE)
    pane = _history(store, clock)
    pane.state.setCurrentIndex(pane.state.findText("Canceled"))
    assert pane.status.text() == "Nothing matches those filters"


def test_an_empty_history_says_there_is_none_yet(app, store, clock) -> None:
    pane = _history(store, clock)
    assert pane.status.text() == "No generation history yet"


# ------------------------------------------- reopen and regenerate (F-41) ---


def test_reopening_an_entry_shows_its_snapshot_settings_and_applied_budget(
    app, store, clock
) -> None:
    _job(store, "job_open", text=ENGLISH)
    _attach(store, "job_open")
    pane = _history(store, clock)
    pane.select_job("job_open")
    assert pane.detail.text.toPlainText() == ENGLISH
    facts = pane.detail.facts.text()
    assert "F1" in facts  # the voice it ran with
    assert "1.00x" in facts  # the tempo it ran with
    assert "20%" in facts  # F-39's applied budget
    assert pane.detail.play_button.isEnabled()


def test_opening_an_entry_neither_plays_nor_regenerates_it(app, store, clock) -> None:
    """F-45 is explicit that neither happens automatically."""
    _job(store, "job_auto")
    _attach(store, "job_auto")
    played: list[str] = []
    regenerated: list[str] = []
    pane = _history(store, clock)
    pane.play_job.connect(played.append)
    pane.regenerate_job.connect(regenerated.append)
    pane.select_job("job_auto")
    pane._activate()
    assert played == []
    assert regenerated == []


def test_enter_on_a_history_row_lands_on_an_action_rather_than_starting_one(
    app, store, clock
) -> None:
    _job(store, "job_kbd")
    _attach(store, "job_kbd")
    played: list[str] = []
    pane = _history(store, clock)
    pane.play_job.connect(played.append)
    QTest.keyClick(pane.tree, Qt.Key.Key_Return)
    assert played == []
    assert pane.detail.first_action() is pane.detail.play_button
    # ...and pressing it is what plays.
    pane.detail.play_button.click()
    assert played == ["job_kbd"]


def test_regenerating_asks_for_a_new_job_and_leaves_the_old_one_alone(
    app, store, clock
) -> None:
    """F-41: regeneration is recorded as a new job and does not overwrite
    the existing result.  The screen only asks; nothing here may mutate."""
    _job(store, "job_again", text=KOREAN)
    before = _attach(store, "job_again")
    asked: list[str] = []
    pane = _history(store, clock)
    pane.regenerate_job.connect(asked.append)
    pane.select_job("job_again")
    pane.detail.regenerate_button.click()

    assert asked == ["job_again"]
    after = store.get_result_for_job("job_again")
    assert after is not None
    assert after.result_id == before.result_id
    assert after.digest == before.digest
    assert store.get_job("job_again").state is JobState.COMPLETE


def test_the_regenerate_action_warns_that_the_audio_will_differ(app, store, clock) -> None:
    """A.5 measured a 0.47 sample delta between two identical runs, so
    F-41's warning is shown where the button is, not in a release note."""
    _job(store, "job_warn")
    _attach(store, "job_warn")
    pane = _history(store, clock)
    pane.select_job("job_warn")
    caution = pane.detail.caution.text()
    assert "new entry" in caution
    assert "not be identical" in caution


def test_an_entry_whose_snapshot_is_gone_cannot_be_regenerated(app, store, clock) -> None:
    _job(store, "job_notext", retention=RetentionMode.ONE_OFF, text=None)
    pane = _history(store, clock)
    pane.select_job("job_notext")
    assert not pane.detail.regenerate_button.isEnabled()
    assert pane.detail.caution.text() == "There is no saved text to generate again from."
    assert pane.detail.text.placeholderText() == "The source text was not kept for this entry."


# -------------------------------------------------- broken results (F-45) ---


def test_a_broken_result_offers_delete_and_regenerate_but_never_play(
    app, store, clock
) -> None:
    _job(store, "job_broken", text=KOREAN)
    _attach(store, "job_broken", exists=False)
    pane = _history(store, clock)
    pane.select_job("job_broken")
    assert not pane.detail.play_button.isEnabled()
    assert not pane.detail.export_button.isEnabled()
    assert pane.detail.regenerate_button.isEnabled()
    assert pane.detail.delete_button.isEnabled()
    assert "missing" in pane.detail.reason.text()


def test_opening_a_broken_entry_records_the_finding_for_next_time(
    app, store, clock
) -> None:
    """F-45's detection is persisted: a finding that lived only in the
    session that noticed would be lost the moment the window closed."""
    _job(store, "job_detect")
    result = _attach(store, "job_detect", exists=False)
    assert store.result_integrity(result.result_id) is ResultIntegrity.UNVERIFIED
    pane = _history(store, clock)
    pane.select_job("job_detect")
    assert store.result_integrity(result.result_id) is ResultIntegrity.MISSING


def test_a_recorded_digest_failure_is_not_overwritten_by_a_size_check(
    app, store, clock
) -> None:
    """A shallow re-check must never turn ``corrupt`` back into ``ok``: the
    file whose digest failed can still have exactly the recorded size."""
    _job(store, "job_digest")
    result = _attach(store, "job_digest")
    store._conn().execute(  # a deep verification elsewhere found the damage
        "UPDATE results SET integrity_state = 'corrupt' WHERE result_id = ?",
        (result.result_id,),
    )
    store._conn().commit()
    pane = _history(store, clock)
    pane.select_job("job_digest")
    assert store.result_integrity(result.result_id) is ResultIntegrity.CORRUPT
    assert not pane.detail.play_button.isEnabled()


def test_an_interrupted_row_shows_the_state_in_words_not_only_in_colour(
    app, store, clock
) -> None:
    """N-30: colour is never the only signal."""
    _job(store, "job_int", state=JobState.INTERRUPTED)
    pane = _history(store, clock)
    assert "Interrupted" in _cells(pane, 0)[2]
    assert pane.tree.topLevelItem(0).toolTip(2)


def test_a_row_cannot_say_expiring_soon_beside_playable(app, store, clock) -> None:
    """The retention cell and the state cell are decided by one expiry, so a
    row that has passed it says so in both places."""
    _job(store, "job_soon", retention=RetentionMode.ONE_OFF)
    _attach(store, "job_soon", expires_at=NOW - 1)
    pane = _history(store, clock)
    when, _voice, state, retention, _length = _cells(pane, 0)
    assert "expired" in retention
    assert "audio expired" in state
    assert when != "—"


def test_a_lost_job_and_a_lost_file_do_not_read_the_same(app, store, clock) -> None:
    """F-25 wants distinguishable reasons: a job that never produced audio
    is a different finding from a result whose file went missing."""
    _job(store, "job_int", state=JobState.INTERRUPTED, created_at=NOW - 2)
    _job(store, "job_gone", created_at=NOW - 1)
    _attach(store, "job_gone", exists=False)
    pane = _history(store, clock)

    pane.select_job("job_int")
    assert pane.detail.reason.property("role") == "danger"
    interrupted = pane.detail.reason.text()

    pane.select_job("job_gone")
    assert pane.detail.reason.property("role") == "warn"
    assert pane.detail.reason.text() != interrupted


def test_a_row_whose_audio_is_missing_says_so_in_its_state_cell(
    app, store, clock
) -> None:
    _job(store, "job_gone")
    result = _attach(store, "job_gone", exists=False)
    store.verify_result(result.result_id)
    pane = _history(store, clock)
    assert _cells(pane, 0)[2] == "Complete · audio missing"


# ------------------------------------------------------- deletion (F-43) ---


def test_the_preview_distinguishes_documents_entries_and_audio(store) -> None:
    doc = store.save_document("Notes", "본문", at=NOW)
    _job(store, "job_del")
    _attach(store, "job_del")
    lines = scope_lines(store.preview_deletion(job_ids=["job_del"], document_ids=[doc.document_id]))
    joined = " | ".join(lines)
    assert "1 document" in joined
    assert "1 history entry" in joined
    assert "1 audio files" in joined or "1 audio" in joined


def test_deleting_only_the_audio_does_not_claim_to_delete_the_entry(store) -> None:
    _job(store, "job_audio")
    _attach(store, "job_audio")
    scope = store.preview_deletion(job_ids=["job_audio"])
    lines = scope_lines(scope, audio_only=True)
    assert not any("history entry" in line for line in lines)
    assert any("audio" in line for line in lines)


def test_deleting_a_document_never_says_a_jobs_saved_text_went_with_it(
    app, store
) -> None:
    """F-43's own sentence: deleting a document alone is never presented as
    having deleted a separate job's source text."""
    doc = store.save_document("Notes", KOREAN, at=NOW)
    _job(store, "job_keep", text=KOREAN)
    scope = store.preview_deletion(document_ids=[doc.document_id])
    dialog = DeleteConfirmDialog(theme.LIGHT, scope, kind="documents")
    words = " ".join(
        child.text() for child in dialog.findChildren(type(dialog.summary))
    )
    assert "history entry" not in words
    assert "Generation history is stored separately" in words
    assert scope.jobs == 0


def test_the_confirmation_promises_exported_wav_files_are_left_alone(app, store) -> None:
    _job(store, "job_x")
    _attach(store, "job_x")
    scope = store.preview_deletion(job_ids=["job_x"])
    dialog = DeleteConfirmDialog(theme.LIGHT, scope, kind="jobs")
    words = " ".join(child.text() for child in dialog.findChildren(type(dialog.summary)))
    assert "WAV files you exported yourself are not touched." in words


def test_deleting_a_job_offers_keeping_the_entry_and_dropping_the_audio(
    app, store
) -> None:
    _job(store, "job_choice")
    _attach(store, "job_choice")
    scope = store.preview_deletion(job_ids=["job_choice"])
    dialog = DeleteConfirmDialog(theme.LIGHT, scope, kind="jobs")
    assert dialog._audio_choice is not None
    assert not dialog.audio_only
    dialog._audio_choice.setChecked(True)
    assert dialog.audio_only
    assert "history entry" not in dialog.summary.text()


def test_a_running_job_must_be_canceled_before_it_can_be_deleted(app, store) -> None:
    """5.3: cancellation first, and a running job is never deleted in part."""
    _job(store, "job_busy", state=JobState.GENERATING)
    scope = store.preview_deletion(job_ids=["job_busy"])
    assert scope.blocked_job_ids == ("job_busy",)
    dialog = DeleteConfirmDialog(theme.LIGHT, scope, kind="jobs")
    assert not dialog.delete_button.isEnabled()


def test_the_delete_button_is_not_the_one_enter_presses(app, store) -> None:
    _job(store, "job_enter")
    scope = store.preview_deletion(job_ids=["job_enter"])
    dialog = DeleteConfirmDialog(theme.LIGHT, scope, kind="jobs")
    assert dialog.cancel_button.isDefault()
    assert not dialog.delete_button.isDefault()


def test_confirming_a_job_deletion_asks_the_window_and_deletes_nothing_itself(
    app, store, clock, monkeypatch
) -> None:
    _job(store, "job_ask")
    _attach(store, "job_ask")
    monkeypatch.setattr(DeleteConfirmDialog, "exec", lambda self: QDialog.DialogCode.Accepted)
    pane = _history(store, clock)
    requests: list[object] = []
    pane.delete_requested.connect(requests.append)
    pane.select_job("job_ask")
    pane.delete_selected()

    assert len(requests) == 1
    request = requests[0]
    assert request.job_ids == ("job_ask",)
    assert request.audio_only is False
    assert request.scope is not None and request.scope.results == 1
    # The screen previews and asks; the store is untouched until the window
    # acts, because unlinking the audio is not the screen's to do.
    assert store.get_result_for_job("job_ask") is not None


def test_several_entries_can_be_deleted_together(app, store, clock, monkeypatch) -> None:
    """F-43 offers deleting related entries together; the rows the user
    picked are the relation this schema actually records."""
    for i in range(3):
        _job(store, f"job_{i}", created_at=NOW - i)
        _attach(store, f"job_{i}")
    monkeypatch.setattr(DeleteConfirmDialog, "exec", lambda self: QDialog.DialogCode.Accepted)
    pane = _history(store, clock)
    requests: list[object] = []
    pane.delete_requested.connect(requests.append)
    pane.tree.selectAll()
    assert pane.delete_button.isEnabled()
    pane.delete_button.click()

    assert len(requests) == 1
    assert set(requests[0].job_ids) == {"job_0", "job_1", "job_2"}
    assert requests[0].scope.jobs == 3
    assert requests[0].scope.results == 3


def test_the_history_delete_button_is_off_until_something_is_chosen(
    app, store, clock
) -> None:
    pane = _history(store, clock)
    assert not pane.delete_button.isEnabled()
    assert not pane.delete_all_button.isEnabled()


def test_declining_a_deletion_asks_for_nothing(app, store, clock, monkeypatch) -> None:
    _job(store, "job_no")
    monkeypatch.setattr(DeleteConfirmDialog, "exec", lambda self: QDialog.DialogCode.Rejected)
    pane = _history(store, clock)
    requests: list[object] = []
    pane.delete_requested.connect(requests.append)
    pane.select_job("job_no")
    pane.delete_selected()
    assert requests == []


def test_deleting_all_history_is_offered_and_leaves_documents_out_of_it(
    app, store, clock, monkeypatch
) -> None:
    store.save_document("Notes", KOREAN, at=NOW)
    _job(store, "job_1", created_at=NOW - 2)
    _job(store, "job_2", created_at=NOW - 1)
    monkeypatch.setattr(DeleteConfirmDialog, "exec", lambda self: QDialog.DialogCode.Accepted)
    pane = _history(store, clock)
    requests: list[object] = []
    pane.delete_requested.connect(requests.append)
    assert pane.delete_all_button.isEnabled()
    pane.delete_all_button.click()

    assert len(requests) == 1
    assert requests[0].all_history is True
    assert requests[0].scope.jobs == 2
    assert requests[0].scope.documents == 0


def test_deleting_documents_asks_with_the_document_ids_only(
    app, store, monkeypatch
) -> None:
    doc = store.save_document("Notes", KOREAN, at=NOW)
    _job(store, "job_unrelated")
    monkeypatch.setattr(DeleteConfirmDialog, "exec", lambda self: QDialog.DialogCode.Accepted)
    pane = _documents(store)
    requests: list[object] = []
    pane.delete_requested.connect(requests.append)
    pane._delete_selected()

    assert len(requests) == 1
    assert requests[0].document_ids == (doc.document_id,)
    assert requests[0].job_ids == ()
    assert store.get_job_text("job_unrelated") == KOREAN


# ------------------------------------------------------- the screen itself ---


def test_the_screen_is_a_plain_widget_with_both_lists(app, store, clock) -> None:
    screen = _screen(store, clock)
    assert screen.tabs.count() == 2
    assert screen.tabs.tabText(0) == "Documents"
    assert screen.tabs.tabText(1) == "History"
    screen.show_history()
    assert screen.tabs.currentWidget() is screen.history
    screen.show_documents()
    assert screen.tabs.currentWidget() is screen.documents


def test_the_screen_forwards_intent_and_never_touches_the_engine(
    app, store, clock
) -> None:
    """The window acts; this screen only says what was asked for."""
    source = Path(library.__file__).read_text(encoding="utf-8")
    assert "jobs.engine" not in source
    assert "from ..app" not in source

    store.save_document("Notes", KOREAN, at=NOW)
    _job(store, "job_fw")
    _attach(store, "job_fw")
    screen = _screen(store, clock)
    seen: list[tuple[str, str]] = []
    screen.open_document.connect(lambda d: seen.append(("open", d)))
    screen.play_job.connect(lambda j: seen.append(("play", j)))
    screen.export_job.connect(lambda j: seen.append(("export", j)))
    screen.regenerate_job.connect(lambda j: seen.append(("regen", j)))

    screen.documents._open_selected()
    screen.select_job("job_fw")
    screen.history.detail.play_button.click()
    screen.history.detail.export_button.click()
    screen.history.detail.regenerate_button.click()

    kinds = [k for k, _ in seen]
    assert kinds == ["open", "play", "export", "regen"]


def test_selecting_a_job_from_outside_switches_to_the_history_tab(
    app, store, clock
) -> None:
    _job(store, "job_a", created_at=NOW - 2)
    _job(store, "job_b", created_at=NOW - 1)
    screen = _screen(store, clock)
    screen.show_documents()
    assert screen.select_job("job_a")
    assert screen.tabs.currentWidget() is screen.history
    assert screen.history.detail.job_id == "job_a"
    assert not screen.select_job("job_missing")


def test_a_store_failure_is_reported_rather_than_swallowed(
    app, store, clock, monkeypatch
) -> None:
    """F-25: the pane says why, and stays usable."""
    from echoact.errors import Code, EchoActError

    def boom(**kwargs):
        raise EchoActError(Code.DB_LOCKED, "The database is busy.")

    pane = HistoryPane(store, theme.LIGHT, manifest=MANIFEST, clock=clock)
    problems: list[object] = []
    pane.problem.connect(problems.append)
    monkeypatch.setattr(store, "list_jobs", boom)
    pane.refresh()
    assert len(problems) == 1
    assert "DB_LOCKED" in pane.status.text()


def _second_row(pane: HistoryPane) -> str:
    """The row ``refresh`` did not already open.

    Reopening the entry that is already current emits nothing, so a test
    about what opening an entry does has to open a different one.
    """
    return pane.tree.topLevelItem(1).data(0, Qt.ItemDataRole.UserRole)


def test_a_result_read_that_fails_does_not_turn_an_expired_entry_playable(
    app, store, clock, monkeypatch
) -> None:
    """F-45 and F-42: a read that did not happen knows nothing about the
    expiry, so it must not overrule the one the list query already found.

    Offering Play beside "the audio has expired" is exactly the
    contradiction ``build_job_row`` promises a row can never show.
    """
    from echoact.errors import Code, EchoActError

    for i, job_id in enumerate(("job_gone_a", "job_gone_b")):
        _job(store, job_id, retention=RetentionMode.ONE_OFF, created_at=NOW - 2 + i)
        _attach(store, job_id, expires_at=NOW - 10)
    pane = _history(store, clock)
    assert "audio expired" in _cells(pane, 1)[2]  # the list row has it right

    def boom(job_id):
        raise EchoActError(Code.DB_LOCKED, "The database is busy.")

    monkeypatch.setattr(store, "get_result_for_job", boom)
    chosen = _second_row(pane)
    assert pane.select_job(chosen)
    assert pane.detail.job_id == chosen

    assert pane.detail.retention.text() == "One-off · the audio has expired"
    assert not pane.detail.play_button.isEnabled()
    assert not pane.detail.export_button.isEnabled()
    assert "expired" in pane.detail.reason.text()


def test_a_failed_store_read_reads_as_an_error_not_as_a_fact_about_the_entry(
    app, store, clock, monkeypatch
) -> None:
    """F-25 and F-42: a busy database is a failure of the panel.

    Reporting it as "the source text was not kept" would be a positive
    claim about retention that nothing has established, and it is the
    opposite of the truth -- the text is there and cannot be read.
    """
    from echoact.errors import Code, EchoActError

    for i, job_id in enumerate(("job_text_a", "job_text_b")):
        _job(store, job_id, text=KOREAN, created_at=NOW - 2 + i)
        _attach(store, job_id)
    pane = _history(store, clock)
    problems: list[object] = []
    pane.problem.connect(problems.append)

    def boom(job_id):
        raise EchoActError(Code.DB_LOCKED, "The database is busy.")

    monkeypatch.setattr(store, "get_job_text", boom)
    chosen = _second_row(pane)
    assert pane.select_job(chosen)
    assert pane.detail.job_id == chosen

    assert len(problems) == 1
    assert not pane.detail.reason.isHidden()
    assert "DB_LOCKED" in pane.detail.reason.text()
    assert "The database is busy." in pane.detail.reason.text()
    assert pane.detail.text.placeholderText() == "The saved text could not be read."
    assert pane.detail.caution.text() == (
        "The saved text could not be read, so it cannot be generated again yet."
    )


def test_an_error_is_shown_beside_the_reason_playback_is_unavailable(
    app, store, clock, monkeypatch
) -> None:
    """F-45's reason and F-25's code are two different findings, and the
    panel has one label for both -- so it shows both rather than letting
    the later one silently overwrite the earlier."""
    from echoact.errors import Code, EchoActError

    for i, job_id in enumerate(("job_both_a", "job_both_b")):
        _job(store, job_id, state=JobState.INTERRUPTED, created_at=NOW - 2 + i)
    pane = _history(store, clock)

    def boom(job_id):
        raise EchoActError(Code.DB_LOCKED, "The database is busy.")

    monkeypatch.setattr(store, "get_job_text", boom)
    assert pane.select_job(_second_row(pane))

    shown = pane.detail.reason.text()
    assert "closed before this finished" in shown
    assert "DB_LOCKED" in shown


# ------------------------------------------------------------ N-30, F-86 ---


def test_every_control_carries_a_name_a_screen_reader_can_read(
    app, store, clock
) -> None:
    store.save_document("Notes", KOREAN, at=NOW)
    _job(store, "job_n30")
    _attach(store, "job_n30")
    screen = _screen(store, clock)
    for button in screen.findChildren(QAbstractButton):
        assert button.text() or button.accessibleName(), button.objectName()
    for combo in screen.findChildren(QComboBox):
        assert combo.accessibleName()
    for edit in screen.findChildren(QLineEdit):
        assert edit.accessibleName()
    assert screen.history.tree.accessibleName()
    assert screen.documents.tree.accessibleName()
    assert screen.history.detail.text.accessibleName()


def _spills(row: QWidget) -> list[str]:
    """Controls whose right edge falls outside the row that holds them."""
    return [
        child.accessibleName() or type(child).__name__
        for child in row.findChildren(QWidget)
        if child.parentWidget() is row and child.geometry().right() > row.width()
    ]


@pytest.mark.parametrize(
    ("width", "height", "scaling"),
    [(1280, 720, "100%"), (640, 360, "200%"), (560, 620, "half a screen")],
)
def test_the_screen_fits_the_narrowest_window_it_has_to(
    app, store, clock, width, height, scaling
) -> None:
    """N-30 sideways, not only downwards.

    1280x720 at 200% OS scaling is 640x360 logical pixels -- emulated by
    halving the size, the way ``test_ui_settings`` does -- and 560 is the
    width a content pane gets beside the rest of the window.  Nothing here
    scrolls horizontally, so a row of controls that cannot wrap would set a
    minimum width the window has to obey and the screen would be clipped
    with no way to reach what is off the edge.
    """
    store.save_document("Notes", KOREAN, at=NOW)
    _job(store, "job_fit")
    _attach(store, "job_fit")
    screen = _screen(store, clock)
    host = QStackedWidget()
    host.addWidget(screen)
    host.show()
    try:
        assert screen.minimumSizeHint().width() <= width
        for show, rows in (
            (screen.show_documents, (screen.documents.pages,)),
            (screen.show_history, (screen.history.filters, screen.history.pages)),
        ):
            show()
            host.resize(width, height)
            host.grab()
            assert host.width() == width, f"the screen forces the window wider at {scaling}"
            for row in rows:
                assert _spills(row) == [], f"clipped sideways at {scaling}"
    finally:
        host.close()


def test_the_screen_fits_a_narrow_window_in_korean_too(app, store, clock) -> None:
    """N-30 holds in both display languages, and Korean sets its own widths."""
    previous = i18n.current()
    host = QStackedWidget()
    try:
        i18n.set_language(i18n.Lang.KO)
        screen = _screen(store, clock)
        host.addWidget(screen)
        host.show()
        screen.show_history()
        host.resize(640, 360)
        host.grab()
        assert screen.minimumSizeHint().width() <= 640
        assert host.width() == 640
        assert _spills(screen.history.filters) == []
    finally:
        host.close()
        i18n.set_language(previous)


def test_both_lists_take_focus_from_the_keyboard(app, store, clock) -> None:
    screen = _screen(store, clock)
    for tree in (screen.documents.tree, screen.history.tree):
        assert tree.focusPolicy() is Qt.FocusPolicy.StrongFocus


def test_the_screen_speaks_korean_when_the_display_language_is_korean(
    app, store, clock
) -> None:
    """F-86: switching the display language changes the chrome and nothing
    else -- the job snapshot below is the same text either way."""
    _job(store, "job_ko", text=ENGLISH)
    previous = i18n.current()
    try:
        i18n.set_language(i18n.Lang.KO)
        screen = _screen(store, clock)
        assert screen.tabs.tabText(0) == "문서"
        assert screen.tabs.tabText(1) == "생성 기록"
        assert screen.history.state.itemText(0) == "모든 상태"
        screen.select_job("job_ko")
        assert screen.history.detail.text.toPlainText() == ENGLISH
    finally:
        i18n.set_language(previous)


#: Strings Korean writes the same way English does.  Kept explicit so that
#: "it looks untranslated" is a decision rather than an oversight.
SAME_IN_KOREAN = {"CPU"}


def test_every_string_this_screen_shows_has_a_korean_form() -> None:
    """F-86, enforced from the source rather than from a hand-kept list, so
    a label added later cannot ship English-only by accident."""
    tree = ast.parse(Path(library.__file__).read_text(encoding="utf-8"))
    literals = {
        node.args[0].value
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "tr"
        and node.args
        and isinstance(node.args[0], ast.Constant)
        and isinstance(node.args[0].value, str)
    }
    assert len(literals) > 40  # the screen really does say this much

    previous = i18n.current()
    try:
        i18n.set_language(i18n.Lang.KO)
        missing = sorted(s for s in literals if i18n.tr(s) == s and s not in SAME_IN_KOREAN)
    finally:
        i18n.set_language(previous)
    assert missing == []
